// Inlines docs/*.md into a typed module the worker imports at runtime.
// Workers have no filesystem, so the markdown must be embedded at build time,
// the same way svelte bundles are embedded via bundles.generated.ts.
//
// Output: src/docs-content.generated.ts, a map of slug -> { title, markdown }.
// The /docs/:slug route renders that markdown with `marked` inside the docs shell.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = join(root, "docs");
const out = join(root, "src", "docs-content.generated.ts");

// Which docs become subpages, and their nav title. Order is the nav order.
// `from` is "docs" (docs/*.md) or "root" (repo-root *.md, e.g. SECURITY.md).
const PAGES = [
  { slug: "security", file: "SECURITY.md", title: "Security posture", from: "root" },
  { slug: "principles", file: "principles.md", title: "Principles", from: "docs" },
  { slug: "feature-tour", file: "feature-tour.md", title: "Feature tour", from: "docs" },
  { slug: "architecture", file: "architecture.md", title: "Architecture", from: "docs" },
  { slug: "feature-matrix", file: "feature-matrix.md", title: "Feature status and limits", from: "docs" },
  { slug: "deploy", file: "deploy.md", title: "Deploy", from: "docs" },
  { slug: "local-development", file: "local-development.md", title: "Local development", from: "docs" },
  { slug: "patterns", file: "patterns.md", title: "Implementation patterns", from: "docs" },
];

const entries = [];
for (const p of PAGES) {
  const base = p.from === "root" ? root : docsDir;
  const path = join(base, p.file);
  try {
    const markdown = readFileSync(path, "utf8");
    entries.push({ slug: p.slug, title: p.title, markdown });
  } catch {
    console.warn(`build-docs: skip ${p.file} (missing)`);
  }
}

const banner = "// GENERATED by scripts/build-docs.mjs. Do not edit by hand.\n// Source: docs/*.md, inlined for the worker (no runtime filesystem).\n\n";
const type = "export type DocPage = { slug: string; title: string; markdown: string };\n\n";
const body = `export const DOC_PAGES: DocPage[] = ${JSON.stringify(entries, null, 2)};\n\n`;
const helper = "export const DOC_PAGE_BY_SLUG: Record<string, DocPage> = Object.fromEntries(DOC_PAGES.map((p) => [p.slug, p]));\n";

writeFileSync(out, banner + type + body + helper);
console.log(`build-docs: wrote ${entries.length} doc pages to ${out}`);
