// Inlines docs/*.md into a typed module the worker imports at runtime.
// Workers have no filesystem, so the markdown must be embedded at build time,
// the same way svelte bundles are embedded via bundles.generated.ts.
//
// Output: src/docs-content.generated.ts, a map of slug -> { title, markdown }.
// The /docs/:slug route renders that markdown with `marked` inside the docs shell.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = join(root, "docs");
const out = join(root, "src", "docs-content.generated.ts");

// Which docs become subpages, and their nav title. Order is the nav order.
const PAGES = [
  { slug: "feature-tour", file: "feature-tour.md", title: "Feature tour" },
  { slug: "architecture", file: "architecture.md", title: "Architecture" },
  { slug: "feature-matrix", file: "feature-matrix.md", title: "Feature status and limits" },
  { slug: "deploy", file: "deploy.md", title: "Deploy" },
  { slug: "local-development", file: "local-development.md", title: "Local development" },
  { slug: "patterns", file: "patterns.md", title: "Implementation patterns" },
];

const available = new Set(readdirSync(docsDir).filter((f) => f.endsWith(".md")));
const entries = [];
for (const p of PAGES) {
  if (!available.has(p.file)) {
    console.warn(`build-docs: skip ${p.file} (missing)`);
    continue;
  }
  const markdown = readFileSync(join(docsDir, p.file), "utf8");
  entries.push({ slug: p.slug, title: p.title, markdown });
}

const banner = "// GENERATED by scripts/build-docs.mjs. Do not edit by hand.\n// Source: docs/*.md, inlined for the worker (no runtime filesystem).\n\n";
const type = "export type DocPage = { slug: string; title: string; markdown: string };\n\n";
const body = `export const DOC_PAGES: DocPage[] = ${JSON.stringify(entries, null, 2)};\n\n`;
const helper = "export const DOC_PAGE_BY_SLUG: Record<string, DocPage> = Object.fromEntries(DOC_PAGES.map((p) => [p.slug, p]));\n";

writeFileSync(out, banner + type + body + helper);
console.log(`build-docs: wrote ${entries.length} doc pages to ${out}`);
